#!/usr/bin/python

import time

FONTE_VIR="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,y,y,y,x,x,x,x,y,y,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,"

FONTE_PON="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"

FONTE_0="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"

FONTE_1="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"

FONTE_2="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_3="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_4="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_5="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_6="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_7="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_8="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"

FONTE_9="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x"


while True:
    antes = time.time()
    abrir = open('valor.txt','r')
    valor = abrir.readline()
    linha = ""
    linha2 = ""    
    for i in range(0,16):
        iter1 = valor.replace(",",FONTE_VIR[i*14:i*14+14])
        iter2 = iter1.replace(".",FONTE_PON[i*14:i*14+14])
        iter3 = iter2.replace("0",FONTE_0[i*46:i*46+46])
        iter4 = iter3.replace("1",FONTE_1[i*46:i*46+46])
        iter5 = iter4.replace("2",FONTE_2[i*46:i*46+46])
        iter6 = iter5.replace("3",FONTE_3[i*46:i*46+46])
        iter7 = iter6.replace("4",FONTE_4[i*46:i*46+46])
        iter8 = iter7.replace("5",FONTE_5[i*46:i*46+46])
        iter9 = iter8.replace("6",FONTE_6[i*46:i*46+46])
        iter10 = iter9.replace("7",FONTE_7[i*46:i*46+46])
        iter11 = iter10.replace("8",FONTE_8[i*46:i*46+46])
        iterF = iter11.replace("9",FONTE_9[i*46:i*46+46])
        linha += iterF + "x,x,x,x," + "\n"
    #for i in range(31,16,-1):
    for i in range(16,32):
        iter1 = valor.replace(",",FONTE_VIR[i*14:i*14+14])
        iter2 = iter1.replace(".",FONTE_PON[i*14:i*14+14])
        iter3 = iter2.replace("0",FONTE_0[i*46:i*46+46])
        iter4 = iter3.replace("1",FONTE_1[i*46:i*46+46])
        iter5 = iter4.replace("2",FONTE_2[i*46:i*46+46])
        iter6 = iter5.replace("3",FONTE_3[i*46:i*46+46])
        iter7 = iter6.replace("4",FONTE_4[i*46:i*46+46])
        iter8 = iter7.replace("5",FONTE_5[i*46:i*46+46])
        iter9 = iter8.replace("6",FONTE_6[i*46:i*46+46])
        iter10 = iter9.replace("7",FONTE_7[i*46:i*46+46])
        iter11 = iter10.replace("8",FONTE_8[i*46:i*46+46])
        iterF = iter11.replace("9",FONTE_9[i*46:i*46+46])
        linha2 += iterF + "x,x,x,x," + "\n"
    linhaF = linha + linha2[::-1]
       
    verFinal1 = linhaF.replace("x","0")
    verFinal2 = verFinal1.replace("y","1")
    verFinal3 = verFinal2.replace('00','0,0')
    verFinal4 = verFinal3.replace(',,',',')
    verFinal5 = verFinal4.replace('\n','')
    verFinal6 = verFinal5.replace(',,',',')
    #print linha
#    print verFinal3

    f = open('arquivo.txt','w')
    f.write(verFinal6)
    f.close()

    debug = open('debug.txt','w')
    debug.write(verFinal4)
    debug.close()

    parada = time.time()-antes
    time.sleep(1-parada)
    print parada
