#!/usr/bin/python

FONTE_VIR="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,"
FONTE_PON="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_0="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_1="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_2="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x," 
FONTE_3="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_4="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_5="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_6="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_7="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_8="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"
FONTE_9="x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,x,y,y,y,y,y,x,x,x,x,y,y,y,x,y,y,y,y,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,x,x,y,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,y,y,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,y,y,x,x,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,x,x,x,x,x,x,x,x,y,y,y,y,x,x,x,x,x,y,y,y,y,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,y,y,y,y,y,y,y,y,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,"

while True:
    abrir = open('valor.txt','r')
    valor = abrir.readline()
    linha = ""

    for i in range(0,32):
        iter1 = valor.replace(",",FONTE_VIR[i*20:i*20+20])
        iter2 = iter1.replace(".",FONTE_PON[i*22:i*22+22])
        iter3 = iter2.replace("0",FONTE_0[i*44:i*44+44])
        iter4 = iter3.replace("1",FONTE_1[i*44:i*44+44])
        iter5 = iter4.replace("2",FONTE_2[i*44:i*44+44])
        iter6 = iter5.replace("3",FONTE_3[i*44:i*44+44])
        iter7 = iter6.replace("4",FONTE_4[i*44:i*44+44])
        iter8 = iter7.replace("5",FONTE_5[i*44:i*44+44])
        iter9 = iter8.replace("6",FONTE_6[i*44:i*44+44])
        iter10 = iter9.replace("7",FONTE_7[i*44:i*44+44])
        iter11 = iter10.replace("8",FONTE_8[i*44:i*44+44])
        iterF = iter11.replace("9",FONTE_9[i*44:i*44+44])
        linha += iterF

    verFinal1 = linha.replace("x","0")
    verFinal2 = verFinal1.replace("y","1")
    f = open('arquivo.txt','w')
    f.write(verFinal2)
    f.close()
